// <auto-generated/>
// Required polyfill: C# 9+ init-only property accessors and positional records use
// System.Runtime.CompilerServices.IsExternalInit, which is not present in netstandard2.0.
// Declaring it here satisfies the compiler without needing a newer runtime.
namespace System.Runtime.CompilerServices;

/// <summary>
/// Polyfill for <c>IsExternalInit</c> required by C# 9+ <c>init</c> property accessors
/// when targeting <c>netstandard2.0</c>.
/// </summary>
internal static class IsExternalInit { }
